name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_on_win_ubuntu_mac:
    name: Build on Windows, Ubuntu & Mac
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: see directory
        run: ls
      - run: npm install -g @quasar/cli
      - run: npm install
      - run: quasar build -m electron
      - run: ls dist/electron
