name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_on_win_ubuntu_mac:
    name: Build on Windows, Ubuntu & Mac
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [macos-latest, ubuntu-20.04, windows-2019]
        node_version: [16.x]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: scipages/gen
          ref: main
          path: gen
      - uses: actions/checkout@v2
        with:
          path: scipages
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - run: |
          ls
          ls gen
          ls scipages
      - run: npm install -g @quasar/cli
      - working-directory: ./scipages
        run: npm install
      - working-directory: ./scipages
        run: quasar build -m electron
      - run: ls scipages/dist/electron
      - uses: actions/upload-artifact@v2
        with:
          name: "${{ matrix.os }}-node-${{ matrix.node_version }}"
          path: scipages/dist/electron/SciPages-*
#      - name: Release
#        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          files: "dist/**"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Build/release Electron app
#          uses: samuelmeuli/action-electron-builder@v1
#          with:
#            # GitHub token, automatically provided to the action
#            # (No need to define this secret in the repo settings)
#            github_token: ${{ secrets.github_token }}
#
#            # If the commit is tagged with a version (e.g. "v1.0.0"),
#            # release the app after building
#            release: ${{ startsWith(github.ref, 'refs/tags/v') }}
